---
- name: Update package lists
  apt:
    update_cache: yes
    upgrade: dist
- name: Install NGINX
  apt:
    name: nginx
    state: present
  notify:
    - Start NGINX

- name: Copy NGINX config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload NGINX
